# Generated by Django 4.1.6 on 2023-05-14 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Disciplina",
            fields=[
                (
                    "CoDisc",
                    models.CharField(max_length=7, primary_key=True, serialize=False),
                ),
                ("Abreviacao", models.CharField(max_length=10, null=True)),
                ("NomeDisc", models.CharField(max_length=60, null=True)),
                (
                    "SemestreIdeal",
                    models.IntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                        ]
                    ),
                ),
                (
                    "CreditosAula",
                    models.IntegerField(choices=[(2, 2), (4, 4)], default=4),
                ),
                (
                    "TipoDisc",
                    models.CharField(
                        choices=[
                            ("obrigatoria", "Obrigatória"),
                            ("optativaCB", "Optativa - Ciclo Básico"),
                            ("optativaSI", "Optativa - Sistemas de informação"),
                        ],
                        default="obrigatoria",
                        max_length=12,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "NroUsp",
                    models.DecimalField(
                        decimal_places=0,
                        default="0",
                        max_digits=7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("NomeProf", models.CharField(default="", max_length=50)),
                ("Apelido", models.CharField(default="", max_length=35)),
                (
                    "Telefone",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=8, null=True
                    ),
                ),
                (
                    "Celular",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=9, null=True
                    ),
                ),
                ("Sala", models.CharField(default="", max_length=25, null=True)),
                ("Email", models.CharField(default="", max_length=30, null=True)),
                ("PG_1_semestre", models.IntegerField(default=0)),
                ("PG_2_semestre", models.IntegerField(default=0)),
                (
                    "consideracao1",
                    models.CharField(
                        blank=True, default=None, max_length=300, null=True
                    ),
                ),
                (
                    "consideracao2",
                    models.CharField(
                        blank=True, default=None, max_length=300, null=True
                    ),
                ),
                (
                    "pos_doc",
                    models.CharField(blank=True, default="", max_length=150, null=True),
                ),
                (
                    "pref_optativas",
                    models.CharField(blank=True, default="", max_length=150, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Turma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "CodTurma",
                    models.DecimalField(decimal_places=0, default=0, max_digits=2),
                ),
                (
                    "Ano",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=4, null=True
                    ),
                ),
                ("NroAlunos", models.IntegerField(blank=True, null=True)),
                (
                    "Eextra",
                    models.CharField(
                        choices=[("S", "Sim"), ("N", "Não")], max_length=1
                    ),
                ),
                (
                    "CoDisc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="table.disciplina",
                    ),
                ),
                (
                    "NroUSP",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="table.professor",
                    ),
                ),
            ],
            options={
                "unique_together": {("Ano", "CodTurma", "CoDisc")},
            },
        ),
        migrations.CreateModel(
            name="Preferencias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "AnoProf",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=4, null=True
                    ),
                ),
                ("Semestre", models.IntegerField(choices=[(1, "impar"), (2, "par")])),
                (
                    "nivel",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3")], default=1
                    ),
                ),
                (
                    "CoDisc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="table.disciplina",
                    ),
                ),
                (
                    "NumProf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="table.professor",
                    ),
                ),
            ],
            options={
                "unique_together": {("NumProf", "CoDisc")},
            },
        ),
        migrations.AddField(
            model_name="disciplina",
            name="professores",
            field=models.ManyToManyField(
                through="table.Preferencias", to="table.professor"
            ),
        ),
        migrations.CreateModel(
            name="Restricao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "periodo",
                    models.CharField(
                        choices=[
                            ("todos_periodos", "Todos períodos do dia"),
                            ("manha", "Manhã"),
                            ("tarde", "Tarde"),
                            ("noite", "Noite"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "dia",
                    models.CharField(
                        choices=[
                            ("todos_dias", "Todos os dias da semana"),
                            ("segunda", "Segunda-feira"),
                            ("terca", "Terça-feira"),
                            ("quarta", "Quarta-feira"),
                            ("quinta", "Quinta-feira"),
                            ("sexta", "Sexta-feira"),
                            ("sabado", "Sábado"),
                            ("domingo", "Domingo"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "semestre",
                    models.CharField(
                        choices=[("1,2", "1 e 2 semestre"), ("2", "2 semestre")],
                        default=None,
                        max_length=15,
                    ),
                ),
                (
                    "nro_usp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="table.professor",
                    ),
                ),
            ],
            options={
                "unique_together": {("nro_usp", "periodo", "dia", "semestre")},
            },
        ),
        migrations.CreateModel(
            name="Dia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "DiaSemana",
                    models.DecimalField(
                        choices=[
                            (0, "Segunda"),
                            (2, "Terça"),
                            (4, "Quarta"),
                            (6, "Quinta"),
                            (8, "Sexta"),
                        ],
                        decimal_places=0,
                        default=2,
                        max_digits=4,
                    ),
                ),
                (
                    "Horario",
                    models.IntegerField(
                        choices=[
                            (0, "8:00 - 09:45h"),
                            (1, "10:15 - 12:00h"),
                            (2, "14:00 - 15:45h"),
                            (4, "16:15-18:00h"),
                            (5, "19:00 - 20:45h"),
                            (7, "21:00 - 22:45h"),
                        ]
                    ),
                ),
                (
                    "Turno",
                    models.CharField(
                        choices=[
                            ("mat", "Matutino"),
                            ("vesp", "Vespertino"),
                            ("Not", "Noturno"),
                        ],
                        default="",
                        max_length=15,
                    ),
                ),
                ("Turmas", models.ManyToManyField(to="table.turma")),
            ],
            options={
                "unique_together": {("Horario", "DiaSemana")},
            },
        ),
    ]
