# Generated by Django 4.1.6 on 2023-05-14 03:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("table", "0002_mtv_restricao"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Mtv_restricao",
            new_name="MtvRestricao",
        ),
    ]
