# Generated by Django 4.1.6 on 2023-05-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("table", "0004_restricao_motivos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mtvrestricao",
            name="mtv",
            field=models.CharField(default="", max_length=300),
        ),
    ]
