# Generated by Django 4.1.6 on 2023-05-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("table", "0006_alter_mtvrestricao_mtv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professor",
            name="consideracao1",
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="professor",
            name="consideracao2",
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
