# Generated by Django 4.1.6 on 2023-05-20 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("table", "0007_alter_professor_consideracao1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professor",
            name="pos_doc",
            field=models.CharField(blank=True, default="", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="professor",
            name="pref_optativas",
            field=models.CharField(blank=True, default="", max_length=300, null=True),
        ),
    ]
