# Generated by Django 4.1.6 on 2023-05-20 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("table", "0008_alter_professor_pos_doc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restricao",
            name="impedimento",
            field=models.BooleanField(
                default=False,
            ),
        ),
    ]
