# Generated by Django 4.1.6 on 2023-09-16 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("table", "0009_alter_restricao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restricao",
            name="motivos",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="table.mtvrestricao",
            ),
        ),
    ]
