# Generated by Django 4.1.6 on 2023-09-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("table", "0010_alter_restricao_motivos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restricao",
            name="semestre",
            field=models.CharField(
                choices=[("1", "1 semestre"), ("2", "2 semestre")],
                default=None,
                max_length=15,
            ),
        ),
    ]
