# Generated by Django 4.1.6 on 2023-10-07 18:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("table", "0012_alter_turma_unique_together_turma_semestreano_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="turma",
            unique_together={("Ano", "CodTurma", "CoDisc", "SemestreAno", "Eextra")},
        ),
    ]
