# Generated by Django 4.1.6 on 2023-11-26 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("table", "0016_anoaberto"),
    ]

    operations = [
        migrations.CreateModel(
            name="RP1Turma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.IntegerField()),
                (
                    "profs_adicionais",
                    models.CharField(
                        blank=True, default=None, max_length=300, null=True
                    ),
                ),
                (
                    "cursos",
                    models.CharField(
                        blank=True, default=None, max_length=300, null=True
                    ),
                ),
                ("ano", models.DecimalField(decimal_places=0, max_digits=4)),
                ("professor_si", models.ManyToManyField(to="table.professor")),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="table.turma"
                    ),
                ),
            ],
            options={
                "unique_together": {("turma", "codigo", "profs_adicionais", "ano")},
            },
        ),
        migrations.CreateModel(
            name="DiaAulaRP1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia_semana",
                    models.CharField(
                        choices=[
                            ("Seg", "Seg"),
                            ("Ter", "Ter"),
                            ("Qua", "Qua"),
                            ("Qui", "Qui"),
                            ("Sex", "Sex"),
                        ],
                        default=None,
                        max_length=3,
                    ),
                ),
                (
                    "horario",
                    models.CharField(
                        choices=[
                            ("08h - 12h", "08h - 12h"),
                            ("14h – 18h", "14h – 18h"),
                            ("19h - 22h45", "19h - 22h45"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                (
                    "turma_rp1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="table.rp1turma"
                    ),
                ),
            ],
            options={
                "unique_together": {("turma_rp1", "dia_semana", "horario")},
            },
        ),
    ]
