# Generated by Django 4.1.6 on 2024-01-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("table", "0018_alter_rp1turma_unique_together_remove_rp1turma_turma"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diaaularp1",
            name="horario",
            field=models.CharField(
                choices=[
                    ("08h - 12h", "08h - 12h"),
                    ("14h – 18h", "14h - 18h"),
                    ("19h - 22h45", "19h - 22h45"),
                ],
                default=None,
                max_length=20,
            ),
        ),
    ]
