# Generated by Django 4.1.6 on 2024-02-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("table", "0019_alter_diaaularp1_horario"),
    ]

    operations = [
        migrations.AddField(
            model_name="turma",
            name="semestre_extra",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
    ]
