# Generated by Django 4.1.6 on 2024-03-01 14:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("table", "0021_disciplina_ativa_professor_em_atividade"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="turma",
            unique_together={
                ("Ano", "CodTurma", "CoDisc", "SemestreAno", "Eextra", "NroUSP")
            },
        ),
    ]
