# Generated by Django 4.1.6 on 2024-03-24 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("table", "0022_alter_turma_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="TadiTurma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.IntegerField()),
                (
                    "curso",
                    models.CharField(
                        blank=True, default=None, max_length=300, null=True
                    ),
                ),
                ("ano", models.DecimalField(decimal_places=0, max_digits=4)),
                ("professor_si", models.ManyToManyField(to="table.professor")),
            ],
            options={
                "unique_together": {("codigo", "curso", "ano")},
            },
        ),
        migrations.CreateModel(
            name="DiaAulaTadi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia_semana",
                    models.CharField(
                        choices=[
                            ("Seg", "Seg"),
                            ("Ter", "Ter"),
                            ("Qua", "Qua"),
                            ("Qui", "Qui"),
                            ("Sex", "Sex"),
                        ],
                        default=None,
                        max_length=3,
                    ),
                ),
                (
                    "horario",
                    models.CharField(
                        choices=[
                            ("8:00 - 09:45h", "8:00 - 09:45h"),
                            ("10:15 - 12:00h", "10:15 - 12:00h"),
                            ("14:00 - 15:45h", "14:00 - 15:45h"),
                            ("16:15-18:00h", "16:15-18:00h"),
                            ("19:00 - 20:45h", "19:00 - 20:45h"),
                            ("21:00 - 22:45h", "21:00 - 22:45h"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                (
                    "turma_tadi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="table.taditurma",
                    ),
                ),
            ],
            options={
                "unique_together": {("turma_tadi", "dia_semana", "horario")},
            },
        ),
    ]
