# Generated by Django 4.1.6 on 2024-05-10 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("table", "0024_alter_preferencias_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TadiTurmaPreview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.IntegerField()),
                ("ano", models.DecimalField(decimal_places=0, max_digits=4)),
                ("professor_si", models.ManyToManyField(to="table.professor")),
            ],
            options={
                "unique_together": {("codigo", "ano")},
            },
        ),
        migrations.CreateModel(
            name="RP1TurmaPreview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.IntegerField()),
                ("ano", models.DecimalField(decimal_places=0, max_digits=4)),
                ("professor_si", models.ManyToManyField(to="table.professor")),
            ],
            options={
                "unique_together": {("codigo", "ano")},
            },
        ),
    ]
