# Generated by Django 4.1.6 on 2024-06-05 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("table", "0026_rp2turmapreview"),
    ]

    operations = [
        migrations.CreateModel(
            name="justificativaMenos8Horas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "justificativa",
                    models.CharField(
                        choices=[
                            ("afastado", "Afastado"),
                            ("compensacao_creditos", "Compensação de Créditos"),
                            ("emprestimo", "Empréstimo"),
                            ("licenca_maternidade", "Licença-Maternidade"),
                            ("licenca_premio", "Licença-Prêmio"),
                            ("sem_contrato", "Sem Contrato"),
                            ("pos_doc", "Pós-Doutorado"),
                        ],
                        default="licenca_premio",
                        max_length=20,
                    ),
                ),
                (
                    "ano",
                    models.DecimalField(decimal_places=0, default=2024, max_digits=4),
                ),
                (
                    "semestre_ano",
                    models.CharField(
                        choices=[("P", "par"), ("I", "impar")],
                        default="P",
                        max_length=1,
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="table.professor",
                    ),
                ),
            ],
            options={
                "unique_together": {("professor", "ano", "semestre_ano")},
            },
        ),
    ]
