# Generated by Django 4.1.6 on 2024-09-17 00:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("table", "0027_justificativamenos8horas"),
    ]

    operations = [
        migrations.AddField(
            model_name="justificativamenos8horas",
            name="texto_justificando",
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="disciplina",
            name="TipoDisc",
            field=models.CharField(
                choices=[
                    ("obrigatoria", "Obrigatória"),
                    ("optativaCB", "Optativa - Ciclo Básico"),
                    ("dea", "Optativa - Sistemas de informação"),
                ],
                default="obrigatoria",
                max_length=12,
            ),
        ),
    ]
